# Generated by Django 2.0.1 on 2019-05-23 01:58

from django.db import migrations

def copy_geo_records(apps, schema_editor):
    NcdbSample = apps.get_model("api", "NcdbSample")
    FIPSRecords = apps.get_model("api", "FIPSRecords")
    db_alias = schema_editor.connection.alias
    for instance in NcdbSample.objects.using(db_alias).all():
        FIPSRecords.objects.using(db_alias).create(
            geo_fips = instance.geo_fips,
            geo_state = instance.geo_state,
            geo_county = instance.geo_county,
            geo_tract = instance.geo_tract
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190523_0158'),
    ]

    operations = [
        migrations.RunPython(copy_geo_records)
    ]
