# Generated by Django 2.0.1 on 2019-05-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ncdbsampleyearly_year'),
    ]

    operations = [
    ]
