# Generated by Django 2.0.1 on 2019-05-23 02:10

from django.db import migrations

def consolidate_years(apps, schema_editor):
    NcdbSampleYearly = apps.get_model("api", "NcdbSampleYearly")
    db_alias = schema_editor.connection.alias
    for instance in NcdbSampleYearly.objects.using(db_alias).all():

        instance.medinc = instance.medinc_90
        instance.medhomeval = instance.medhomeval_90
        instance.medrentval = instance.medrentval_90
        instance.ownshare = instance.ownshare_90
        instance.whiteshare = instance.whiteshare_90
        instance.blackshare = instance.blackshare_90
        instance.hispshare = instance.hispshare_90
        instance.asothshare = instance.asothshare_90
        instance.rentcbshare = instance.rentcbshare_90
        instance.povrate = instance.povrate_90
        instance.bachshare = instance.bachshare_90
        instance.metmedinc = instance.metmedinc_90
        instance.metmedhomeval = instance.metmedhomeval_90
        instance.metmedrentval = instance.metmedrentval_90
        instance.metownshare = instance.metownshare_90
        instance.metwhiteshare = instance.metwhiteshare_90
        instance.metblackshare = instance.metblackshare_90
        instance.methispshare = instance.methispshare_90
        instance.metasothshare = instance.metasothshare_90
        instance.metrentcbshare = instance.metrentcbshare_90
        instance.metpovrate = instance.metpovrate_90
        instance.metbachshare = instance.metbachshare_90
        instance.year = 1990
        instance.save()

        instance.pk = None
        instance.medinc = instance.medinc_00
        instance.medhomeval = instance.medhomeval_00
        instance.medrentval = instance.medrentval_00
        instance.ownshare = instance.ownshare_00
        instance.whiteshare = instance.whiteshare_00
        instance.blackshare = instance.blackshare_00
        instance.hispshare = instance.hispshare_00
        instance.asothshare = instance.asothshare_00
        instance.rentcbshare = instance.rentcbshare_00
        instance.povrate = instance.povrate_00
        instance.bachshare = instance.bachshare_00
        instance.metmedinc = instance.metmedinc_00
        instance.metmedhomeval = instance.metmedhomeval_00
        instance.metmedrentval = instance.metmedrentval_00
        instance.metownshare = instance.metownshare_00
        instance.metwhiteshare = instance.metwhiteshare_00
        instance.metblackshare = instance.metblackshare_00
        instance.methispshare = instance.methispshare_00
        instance.metasothshare = instance.metasothshare_00
        instance.metrentcbshare = instance.metrentcbshare_00
        instance.metpovrate = instance.metpovrate_00
        instance.metbachshare = instance.metbachshare_00
        instance.year = 2000
        instance.save()

        instance.pk = None
        instance.medinc = instance.medinc_10
        instance.medhomeval = instance.medhomeval_10
        instance.medrentval = instance.medrentval_10
        instance.ownshare = instance.ownshare_10
        instance.whiteshare = instance.whiteshare_10
        instance.blackshare = instance.blackshare_10
        instance.hispshare = instance.hispshare_10
        instance.asothshare = instance.asothshare_10
        instance.rentcbshare = instance.rentcbshare_10
        instance.povrate = instance.povrate_10
        instance.bachshare = instance.bachshare_10
        instance.metmedinc = instance.metmedinc_10
        instance.metmedhomeval = instance.metmedhomeval_10
        instance.metmedrentval = instance.metmedrentval_10
        instance.metownshare = instance.metownshare_10
        instance.metwhiteshare = instance.metwhiteshare_10
        instance.metblackshare = instance.metblackshare_10
        instance.methispshare = instance.methispshare_10
        instance.metasothshare = instance.metasothshare_10
        instance.metrentcbshare = instance.metrentcbshare_10
        instance.metpovrate = instance.metpovrate_10
        instance.metbachshare = instance.metbachshare_10
        instance.tractpopulation = instance.tractpopulation2010
        instance.year = 2010
        instance.save()

        instance.pk = None
        instance.medinc = instance.medinc_17
        instance.medhomeval = instance.medhomeval_17
        instance.medrentval = instance.medrentval_17
        instance.ownshare = instance.ownshare_17
        instance.whiteshare = instance.whiteshare_17
        instance.blackshare = instance.blackshare_17
        instance.hispshare = instance.hispshare_17
        instance.asothshare = instance.asothshare_17
        instance.rentcbshare = instance.rentcbshare_17
        instance.povrate = instance.povrate_17
        instance.bachshare = instance.bachshare_17
        instance.metmedinc = instance.metmedinc_17
        instance.metmedhomeval = instance.metmedhomeval_17
        instance.metmedrentval = instance.metmedrentval_17
        instance.metownshare = instance.metownshare_17
        instance.metwhiteshare = instance.metwhiteshare_17
        instance.metblackshare = instance.metblackshare_17
        instance.methispshare = instance.methispshare_17
        instance.metasothshare = instance.metasothshare_17
        instance.metrentcbshare = instance.metrentcbshare_17
        instance.metpovrate = instance.metpovrate_17
        instance.metbachshare = instance.metbachshare_17
        instance.year = 2017
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190523_0209'),
    ]

    operations = [
        migrations.RunPython(consolidate_years)
    ]
