# Generated by Django 2.0.1 on 2019-05-23 02:30

from django.db import migrations

def consolidate_change_years(apps, schema_editor):
    NcdbSampleChanges = apps.get_model("api", "NcdbSampleChanges")
    db_alias = schema_editor.connection.alias
    for instance in NcdbSampleChanges.objects.using(db_alias).all():

        # 1990 - 2017
        instance.chrent = instance.chrent_9017
        instance.chinc = instance.chinc_9017
        instance.chhomeval = instance.chhomeval_9017
        instance.chbachshare = instance.chbachshare_9017
        instance.chwhiteshare = instance.chwhiteshare_9017
        instance.chblackshare = instance.chblackshare_9017
        instance.chhispshare = instance.chhispshare_9017
        instance.chasothshare = instance.chasothshare_9017
        instance.chownshare = instance.chownshare_9017
        instance.chpovrate = instance.chpovrate_9017
        instance.chrentcbshare = instance.chrentcbshare_9017
        instance.metchbachshare = instance.metchbachshare_9017
        instance.metchrent = instance.metchrent_9017
        instance.metchhomeval = instance.metchhomeval_9017
        instance.metchpovrate = instance.metchpovrate_9017
        instance.metchownshare = instance.metchownshare_9017
        instance.metchrentcbshare = instance.metchrentcbshare_9017
        instance.metchwhiteshare = instance.metchwhiteshare_9017
        instance.metchblackshare = instance.metchblackshare_9017
        instance.metchhispshare = instance.metchhispshare_9017
        instance.metchasothshare = instance.metchasothshare_9017
        instance.start_year = 1990
        instance.end_year = 2017
        instance.save()

        # 1990 - 2016
        instance.pk = None
        instance.metchrent = instance.metchrent_9016
        instance.metchhomeval = instance.metchhomeval_9016
        instance.start_year = 1990
        instance.end_year = 2016
        instance.save()

        # 1990 - 2000
        instance.pk = None
        instance.metchbachshare = instance.metchbachshare_9000
        instance.metchrent = instance.metchrent_9000
        instance.metchhomeval = instance.metchhomeval_9000
        instance.metchpovrate = instance.metchpovrate_9000
        instance.metchownshare = instance.metchownshare_9000
        instance.metchrentcbshare = instance.metchrentcbshare_9000
        instance.metchwhiteshare = instance.metchwhiteshare_9000
        instance.metchblackshare = instance.metchblackshare_9000
        instance.metchhispshare = instance.metchhispshare_9000
        instance.metchasothshare = instance.metchasothshare_9000
        instance.start_year = 1990
        instance.end_year = 2000
        instance.save()

        # 2000 - 2017
        instance.pk = None
        instance.chrent = instance.chrent_0017
        instance.chinc = instance.chinc_0017
        instance.chhomeval = instance.chhomeval_0017
        instance.chbachshare = instance.chbachshare_0017
        instance.chwhiteshare = instance.chwhiteshare_0017
        instance.chblackshare = instance.chblackshare_0017
        instance.chhispshare = instance.chhispshare_0017
        instance.chasothshare = instance.chasothshare_0017
        instance.chownshare = instance.chownshare_0017
        instance.chpovrate = instance.chpovrate_0017
        instance.chrentcbshare = instance.chrentcbshare_0017
        instance.metchbachshare = instance.metchbachshare_0017
        instance.metchrent = instance.metchrent_0017
        instance.metchhomeval = instance.metchhomeval_0017
        instance.metchpovrate = instance.metchpovrate_0017
        instance.metchownshare = instance.metchownshare_0017
        instance.metchrentcbshare = instance.metchrentcbshare_0017
        instance.metchwhiteshare = instance.metchwhiteshare_0017
        instance.metchblackshare = instance.metchblackshare_0017
        instance.metchhispshare = instance.metchhispshare_0017
        instance.metchasothshare = instance.metchasothshare_0017
        instance.start_year = 2000
        instance.end_year = 2017
        instance.save()

        # 2000 - 2010
        instance.pk = None
        instance.metchbachshare = instance.metchbachshare_0010
        instance.metchrent = instance.metchrent_0010
        instance.metchhomeval = instance.metchhomeval_0010
        instance.metchpovrate = instance.metchpovrate_0010
        instance.metchownshare = instance.metchownshare_0010
        instance.metchrentcbshare = instance.metchrentcbshare_0010
        instance.metchwhiteshare = instance.metchwhiteshare_0010
        instance.metchblackshare = instance.metchblackshare_0010
        instance.metchhispshare = instance.metchhispshare_0010
        instance.metchasothshare = instance.metchasothshare_0010
        instance.start_year = 2000
        instance.end_year = 2010
        instance.save()

        # 2010 - 2017
        instance.pk = None
        instance.chrent = instance.chrent_1017
        instance.chinc = instance.chinc_1017
        instance.chhomeval = instance.chhomeval_1017
        instance.chbachshare = instance.chbachshare_1017
        instance.chwhiteshare = instance.chwhiteshare_1017
        instance.chblackshare = instance.chblackshare_1017
        instance.chhispshare = instance.chhispshare_1017
        instance.chasothshare = instance.chasothshare_1017
        instance.chownshare = instance.chownshare_1017
        instance.chpovrate = instance.chpovrate_1017
        instance.chrentcbshare = instance.chrentcbshare_1017
        instance.metchbachshare = instance.metchbachshare_1017
        instance.metchrent = instance.metchrent_1017
        instance.metchhomeval = instance.metchhomeval_1017
        instance.metchpovrate = instance.metchpovrate_1017
        instance.metchownshare = instance.metchownshare_1017
        instance.metchrentcbshare = instance.metchrentcbshare_1017
        instance.metchwhiteshare = instance.metchwhiteshare_1017
        instance.metchblackshare = instance.metchblackshare_1017
        instance.metchhispshare = instance.metchhispshare_1017
        instance.metchasothshare = instance.metchasothshare_1017
        instance.start_year = 2000
        instance.end_year = 2017
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190523_0230'),
    ]

    operations = [
        migrations.RunPython(consolidate_change_years)
    ]
