# Generated by Django 2.0.1 on 2019-05-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190523_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncdbsampleyearly',
            name='fips_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FIPSRecords'),
        ),
    ]
