# Generated by Django 2.0.1 on 2019-05-27 22:21

from django.db import migrations

def add_fips_foreign_key_yearly(apps, schema_editor):
    NcdbSampleYearly = apps.get_model("api", "NcdbSampleYearly")
    fips = apps.get_model("api", "FIPSRecords")
    for fipsinstance in fips.objects.all():
        for yearlyinstance in NcdbSampleYearly.objects.all().filter(geo_fips=fipsinstance.geo_fips):
            yearlyinstance.fips_code = fipsinstance
            yearlyinstance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ncdbsampleyearly_fips_code'),
    ]

    operations = [
        migrations.RunPython(add_fips_foreign_key_yearly)
    ]
