# Generated by Django 2.0.1 on 2019-05-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190527_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncdbsamplechanges',
            name='fips_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FIPSRecords'),
        ),
    ]
