# Generated by Django 2.0.1 on 2019-05-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190528_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncdbsamplechanges',
            name='geo_fips',
        ),
        migrations.RemoveField(
            model_name='ncdbsampleyearly',
            name='geo_fips',
        ),
    ]
