# Generated by Django 2.0.1 on 2019-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_ncdbsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmdaOrwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('actiontakentype', models.TextField(blank=True, db_column='ActionTakenType', null=True)),
                ('agencyname', models.TextField(blank=True, db_column='AgencyName', null=True)),
                ('applicant1_sex_name', models.TextField(blank=True, null=True)),
                ('applicant1race', models.TextField(blank=True, db_column='Applicant1Race', null=True)),
                ('applicant2_sex_name', models.TextField(blank=True, null=True)),
                ('applicant2race', models.TextField(blank=True, db_column='Applicant2Race', null=True)),
                ('applicantincome', models.IntegerField(blank=True, db_column='ApplicantIncome', null=True)),
                ('censustract', models.TextField(blank=True, db_column='CensusTract', null=True)),
                ('countycode', models.TextField(blank=True, db_column='CountyCode', null=True)),
                ('denialreason1', models.TextField(blank=True, db_column='DenialReason1', null=True)),
                ('denialreason2', models.TextField(blank=True, db_column='DenialReason2', null=True)),
                ('denialreason3', models.TextField(blank=True, db_column='DenialReason3', null=True)),
                ('editstatus', models.TextField(blank=True, db_column='EditStatus', null=True)),
                ('hoepa_loan', models.TextField(blank=True, db_column='HOEPA_loan', null=True)),
                ('hud_median_family_income', models.IntegerField(blank=True, null=True)),
                ('lienstatus', models.TextField(blank=True, db_column='LienStatus', null=True)),
                ('loanamount', models.IntegerField(blank=True, db_column='LoanAmount', null=True)),
                ('loanpurpose', models.TextField(blank=True, db_column='LoanPurpose', null=True)),
                ('loantype', models.TextField(blank=True, db_column='LoanType', null=True)),
                ('minority_population', models.FloatField(blank=True, null=True)),
                ('msaofproperty', models.TextField(blank=True, db_column='MSAofProperty', null=True)),
                ('number_of_1_to_4_family_units', models.IntegerField(blank=True, null=True)),
                ('number_of_owner_occupied_units', models.IntegerField(blank=True, null=True)),
                ('occupancy', models.TextField(blank=True, db_column='Occupancy', null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('preapprovals', models.TextField(blank=True, db_column='Preapprovals', null=True)),
                ('propertytype', models.TextField(blank=True, db_column='PropertyType', null=True)),
                ('purchasertype', models.TextField(blank=True, db_column='PurchaserType', null=True)),
                ('ratespread', models.FloatField(blank=True, db_column='RateSpread', null=True)),
                ('respondent_id', models.TextField(blank=True, db_column='Respondent_ID', null=True)),
                ('sequencenumber', models.IntegerField(blank=True, db_column='SequenceNumber', null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('tract_to_msamd_income', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hmda_orwa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': True,
            },
        ),
    ]
