# Generated by Django 2.0.1 on 2019-06-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_hmdaorwa_spatialrefsys'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tct_fips', models.BigIntegerField(blank=True, null=True)),
                ('total_loans', models.BigIntegerField(blank=True, null=True)),
                ('total_poc_loans', models.FloatField(blank=True, null=True)),
                ('share_loans_to_poc', models.FloatField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('pop_total', models.BigIntegerField(blank=True, null=True)),
                ('poc_total', models.BigIntegerField(blank=True, null=True)),
                ('share_poc', models.FloatField(blank=True, null=True)),
                ('total_homeowners', models.BigIntegerField(blank=True, null=True)),
                ('poc_owners', models.BigIntegerField(blank=True, null=True)),
                ('share_poc_owners', models.FloatField(blank=True, null=True)),
                ('loan_lq', models.FloatField(blank=True, null=True)),
                ('brks_lq', models.TextField(blank=True, db_column='brks.lq', null=True)),
            ],
            options={
                'db_table': 'total_loans',
                'managed': True,
            },
        ),
    ]
