# Generated by Django 2.0.1 on 2019-07-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190630_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcdbPopulationAddendum',
            fields=[
                ('index', models.BigIntegerField(primary_key=True)),
                ('geo_fips', models.BigIntegerField(blank=True, db_column='Geo_FIPS', null=True)),
                ('totalpopulation_90', models.IntegerField(blank=True, db_column='TotalPopulation_90', null=True)),
                ('totalpopulation_00', models.IntegerField(blank=True, db_column='TotalPopulation_00', null=True)),
                ('totalpopulation_10', models.IntegerField(blank=True, db_column='TotalPopulation_10', null=True)),
                ('totalpopulation_17', models.IntegerField(blank=True, db_column='TotalPopulation_17', null=True)),
            ],
            options={
                'db_table': 'ncdb_population_addendum',
                'managed': True,
            },
        ),
        # migrations.RemoveField(
        #     model_name='hmdaorwa',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='totalloans',
        #     name='id',
        # ),
    ]
