# Generated by Django 2.0.1 on 2019-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190717_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcdbMetroYearlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('metroname', models.TextField(blank=True, null=True)),
                ('metmedinc', models.FloatField(blank=True, null=True)),
                ('metmedhomeval', models.FloatField(blank=True, null=True)),
                ('metmedrentval', models.FloatField(blank=True, null=True)),
                ('metownshare', models.FloatField(blank=True, null=True)),
                ('metwhiteshare', models.FloatField(blank=True, null=True)),
                ('metblackshare', models.FloatField(blank=True, null=True)),
                ('methispshare', models.FloatField(blank=True, null=True)),
                ('metasothshare', models.FloatField(blank=True, null=True)),
                ('metrentcbshare', models.FloatField(blank=True, null=True)),
                ('metpovrate', models.FloatField(blank=True, null=True)),
                ('metbachshare', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
