# Generated by Django 2.0.1 on 2019-07-26 04:40

from django.db import migrations

def populate_ncdb_metro_yearly(apps, schema_editor):
    ncdbyearly = apps.get_model("api", "NcdbSampleYearly")
    metroyearly = apps.get_model("api", "NcdbMetroYearlyData")
    rows = ncdbyearly.objects.order_by('year', 'metroname').distinct('year', 'metroname')

    for row in rows:
        new_object = metroyearly.objects.create(
            year = row.year,
            metroname = row.metroname,
            metmedinc = row.metmedinc,
            metmedhomeval = row.metmedhomeval,
            metmedrentval = row.metmedrentval,
            metownshare = row.metownshare,
            metwhiteshare = row.metwhiteshare,
            metblackshare = row.metblackshare,
            methispshare = row.methispshare,
            metasothshare = row.metasothshare,
            metrentcbshare = row.metrentcbshare,
            metpovrate = row.metpovrate,
            metbachshare = row.metbachshare
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190726_0440'),
    ]

    operations = [
        migrations.RunPython(populate_ncdb_metro_yearly)
    ]
